version: "3.7"
services:
  db:
    image: postgres:12
    environment:
      POSTGRES_DB: ${DATABASE_NAME}
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - ${DATABASE_PORT}:5432
    restart: always

  composer:
    build:
      context: docker/php
      args:
        APP_ENV: "${APP_ENV}"
    working_dir: /var/www/Phalcon
    volumes:
      - ./Backend:/var/www/Phalcon
      - composer-cache-volume:/tmp/cache
    entrypoint: composer install

  redis:
    build: docker/redis
    expose:
      - "6379"
    restart: always

  php:
    build:
      context: docker/php
      args:
        APP_ENV: "${APP_ENV}"
    working_dir: /var/www/Phalcon
    volumes:
      - ./Backend:/var/www/Phalcon
      - composer-cache-volume:/tmp/cache
      - sock-volume:/sock
    restart: always
    depends_on:
      - db
      - composer
      - redis

  backend:
    build: docker/nginx
    volumes:
      - ./Backend:/var/www/Phalcon
      - sock-volume:/sock
    ports:
      - ${BACKEND_PORT}:80
    restart: always
    depends_on:
      - php

volumes:
  sock-volume:
  composer-cache-volume:
  db-data: